spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    props:
      # 打印sql
      sql.show: true
      check:
        table:
          metadata:
            # 是否在启动时检查分表元数据一致性
            enabled: false
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        #type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:32000/game
        username: root
        password: 123456
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        #type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:32002/game
        username: root
        password: 123456
    sharding:
      # 默认数据源
      default-data-source-name: ds0

      #默认主键生成策略
      default-key-generator:
        type: SNOWFLAKE
        column: id
        worker:
          id: order
        max:
          tolerate:
            time:
              difference:
                milliseconds: 1
      #默认分库策略，按照id划分，id除以2取模并加上1（因为本demo数据库名称是从1开始的），如果结果为1就在ssd1库，如果结果为2就在ssd2库
      default-database-strategy:
        inline:
          sharding-column: id
          algorithm-expression: ds$->{id % 2}

      #分表策略
      tables:
        t_pet:
          #主键生成策略
          #          key-generator:
          #            column: id
          #            type: SNOWFLAKE
          actual-data-nodes: ds$->{0..1}.t_pet_$->{0..1}
          #在本库中分表策略，按照年龄分表，通过年龄除以2取模，如果为0就存到t_pet_0,如果为1就存到t_pet_1
          table-strategy:
            inline:
              sharding-column: age
              algorithm-expression: t_pet_$->{age % 2}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.dao.entity