apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cmak.name" . }}-clusters
  labels:
    {{- include "cmak.labels" . | nindent 4 }}
data:
  {{- range .Values.cmak.clusters }}
  {{ .name }}.json: |-
    {{- mergeOverwrite (deepCopy $.Values.cmak.clustersCommon) . | toJson | nindent 4 }}
  {{- end }}

